final Map<String, Map<String, List<Halisaha>>> data = {
  'Tekirdağ': {
    'Süleymanpaşa': [
      Halisaha(
        name: 'Class Halısahası',
        latitude: 40.97297,
        longitude: 29.15019,
        mapLink: 'https://maps.app.goo.gl/7y228dRTrSdtvXST8',
        phoneNumber: '02822621151',
        primaryImageUrl: 'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        imageUrls: [
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        ],
        isIndoor: true,
        hasShower: false,
        hasParking: true,
        city: 'Tekirdağ',
        district: 'Süleymanpaşa',
      ),

      Halisaha(
        name: 'Değirmenaltı Bahçe Halısahası',
        latitude: 40.97297,
        longitude: 29.15019,
        mapLink: 'https://maps.app.goo.gl/1YRg8bqT2CQ4btLfA',
        phoneNumber: '02822931616',
        primaryImageUrl: 'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        imageUrls: [
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        ],
        isIndoor: true,
        hasShower: true,
        hasParking: true,
        city: 'Tekirdağ',
        district: 'Süleymanpaşa',
      ),
      Halisaha(
        name: 'Er-Ba Arena Halısahası',
        latitude: 40.97297,
        longitude: 29.15019,
        mapLink: 'https://maps.app.goo.gl/G5n1Nni3gr7LFEDJ9',
        phoneNumber: '0282 262 6152',
        primaryImageUrl: 'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        imageUrls: [
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        ],
        isIndoor: true,
        hasShower: true,
        hasParking: true,
        city: 'Tekirdağ',
        district: 'Süleymanpaşa',
      ),

    ],
    'Çorlu': [
      Halisaha(
        name: 'Ataş Halısahası',
        latitude: 40.97297,
        longitude: 29.15019,
        mapLink: 'https://maps.app.goo.gl/kcKHEwoGKbXms7Jy6',
        phoneNumber: '0282 692 2905',
        primaryImageUrl: 'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        imageUrls: [
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        ],
        isIndoor: true,
        hasShower: true,
        hasParking: true,
        city: 'Tekirdağ',
        district: 'Çorlu',
      ),
      Halisaha(
        name: 'Garp Halısahası',
        latitude: 40.97297,
        longitude: 29.15019,
        mapLink: 'https://maps.app.goo.gl/w65ppSafo3XSQfXU8',
        phoneNumber: '02826925354',
        primaryImageUrl: 'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        imageUrls: [
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        ],
        isIndoor: true,
        hasShower: true,
        hasParking: true,
        city: 'Tekirdağ',
        district: 'Çorlu',
      ),

    ],
  },
  'İstanbul': {
    'Bağcılar': [
      Halisaha(
        name: 'Doğuş Halısahası',
        latitude: 40.97297,
        longitude: 29.15019,
        mapLink: 'https://maps.app.goo.gl/t8jJiq57zJYbaU247',
        phoneNumber: '0212 515 90 94',
        primaryImageUrl: 'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        imageUrls: [
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        ],
        isIndoor: true,
        hasShower: true,
        hasParking: true,
        city: 'İstanbul',
        district: 'Bağcılar',
      ),

      Halisaha(
        name: 'Ayyıldız Halısahası',
        latitude: 40.97297,
        longitude: 29.15019,
        mapLink: 'https://maps.app.goo.gl/5bMLn3p3H91MLQVC8',
        phoneNumber: '(0212) 446 35 90',
        primaryImageUrl: 'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        imageUrls: [
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        ],
        isIndoor: true,
        hasShower: true,
        hasParking: true,
        city: 'İstanbul',
        district: 'Bağcılar',
      ),
      Halisaha(
        name: 'Ayar Halısahası',
        latitude: 40.97297,
        longitude: 29.15019,
        mapLink: 'https://maps.app.goo.gl/dgJx29jd4NCxcn5PA',
        phoneNumber: '0212 630 50 65',
        primaryImageUrl: 'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        imageUrls: [
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        ],
        isIndoor: true,
        hasShower: true,
        hasParking: true,
        city: 'İstanbul',
        district: 'Bağcılar',
      ),

      Halisaha(
        name: 'Cfs Halısahası',
        latitude: 40.97297,
        longitude: 29.15019,
        mapLink: 'https://maps.app.goo.gl/DEjYU8x77MYJHCBg7',
        phoneNumber: '0212 446 20 47',
        primaryImageUrl: 'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        imageUrls: [
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        ],
        isIndoor: true,
        hasShower: true,
        hasParking: true,
        city: 'İstanbul',
        district: 'Bağcılar',
      ),

      Halisaha(
        name: 'Tunçbilek Halısahası',
        latitude: 40.97297,
        longitude: 29.15019,
        mapLink: 'https://maps.app.goo.gl/oTqeSdrSemVcYKMY8',
        phoneNumber: '0212 630 47 25',
        primaryImageUrl: 'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        imageUrls: [
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        ],
        isIndoor: true,
        hasShower: true,
        hasParking: true,
        city: 'İstanbul',
        district: 'Bağcılar',
      ),
      Halisaha(
        name: 'Peyami Safa Halısahası',
        latitude: 40.97297,
        longitude: 29.15019,
        mapLink: 'https://maps.app.goo.gl/SHKyKvFGNFgYABC9A',
        phoneNumber: '0541 560 28 28',
        primaryImageUrl: 'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        imageUrls: [
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        ],
        isIndoor: true,
        hasShower: true,
        hasParking: true,
        city: 'İstanbul',
        district: 'Bağcılar',
      ),


    ],
    'Bahçelievler': [
      Halisaha(
        name: 'Üçler Halısahası',
        latitude: 40.97297,
        longitude: 29.15019,
        mapLink: 'https://maps.app.goo.gl/1DxnyEPuDGMmiRYKA',
        phoneNumber: '0533 092 05 22',
        primaryImageUrl: 'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        imageUrls: [
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        ],
        isIndoor: true,
        hasShower: true,
        hasParking: true,
        city: 'İstanbul',
        district: 'Bahçelievler',
      ),

      Halisaha(
        name: 'Kocasinan Halısahası',
        latitude: 40.97297,
        longitude: 29.15019,
        mapLink: 'https://maps.app.goo.gl/6YbP6P21pPq5RiWM8',
        phoneNumber: '0212 550 71 50',
        primaryImageUrl: 'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        imageUrls: [
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        ],
        isIndoor: true,
        hasShower: true,
        hasParking: true,
        city: 'İstanbul',
        district: 'Bahçelievler',
      ),
      Halisaha(
        name: 'Yaşam Halısahası',
        latitude: 40.97297,
        longitude: 29.15019,
        mapLink: 'https://maps.app.goo.gl/CY4DkM3dZyH3aEzz8',
        phoneNumber: '0212 474 20 26',
        primaryImageUrl: 'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        imageUrls: [
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        ],
        isIndoor: true,
        hasShower: true,
        hasParking: true,
        city: 'İstanbul',
        district: 'Bahçelievler',
      ),
      Halisaha(
        name: 'Çağrı Halısahası',
        latitude: 40.97297,
        longitude: 29.15019,
        mapLink: 'https://maps.app.goo.gl/8cXRqYb5EeoVQvNq6',
        phoneNumber: '0212 550 59 70',
        primaryImageUrl: 'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        imageUrls: [
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        ],
        isIndoor: true,
        hasShower: true,
        hasParking: true,
        city: 'İstanbul',
        district: 'Bahçelievler',
      ),
      Halisaha(
        name: 'Olimpik Spor Halısahası',
        latitude: 40.97297,
        longitude: 29.15019,
        mapLink: 'https://maps.app.goo.gl/AJXHZmZGnJLjmAVP6',
        phoneNumber: '05349262928',
        primaryImageUrl: 'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        imageUrls: [
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        ],
        isIndoor: true,
        hasShower: true,
        hasParking: true,
        city: 'İstanbul',
        district: 'Bahçelievler',
      ),
      Halisaha(
        name: 'Kuyumcukent Halısahası',
        latitude: 40.97297,
        longitude: 29.15019,
        mapLink: 'https://maps.app.goo.gl/ZzwnQxqQSncZTH7n8',
        phoneNumber: '05327915841',
        primaryImageUrl: 'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        imageUrls: [
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        ],
        isIndoor: true,
        hasShower: true,
        hasParking: true,
        city: 'İstanbul',
        district: 'Bahçelievler',
      ),
      Halisaha(
        name: 'Burak Halısahası',
        latitude: 40.97297,
        longitude: 29.15019,
        mapLink: 'https://maps.app.goo.gl/w1P8eesogCYgLW4d6',
        phoneNumber: '0212 651 94 15',
        primaryImageUrl: 'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        imageUrls: [
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        ],
        isIndoor: true,
        hasShower: true,
        hasParking: true,
        city: 'İstanbul',
        district: 'Bahçelievler',
      ),
      Halisaha(
        name: 'Yenibosna Halısahası',
        latitude: 40.97297,
        longitude: 29.15019,
        mapLink: 'https://maps.app.goo.gl/aQYoXwVTCmraxuQMA',
        phoneNumber: '02124843800',
        primaryImageUrl: 'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        imageUrls: [
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        ],
        isIndoor: true,
        hasShower: true,
        hasParking: true,
        city: 'İstanbul',
        district: 'Bahçelievler',
      ),
      Halisaha(
        name: 'Hacıoğlu Halısahası',
        latitude: 40.97297,
        longitude: 29.15019,
        mapLink: 'https://maps.app.goo.gl/wxXeR88NFEocjKxq6',
        phoneNumber: '05073215751',
        primaryImageUrl: 'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        imageUrls: [
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        ],
        isIndoor: true,
        hasShower: true,
        hasParking: true,
        city: 'İstanbul',
        district: 'Bahçelievler',
      ),
      Halisaha(
        name: 'Best Spor Halısahası',
        latitude: 40.97297,
        longitude: 29.15019,
        mapLink: 'https://maps.app.goo.gl/K2JefZi2BGtRrAJo7',
        phoneNumber: '05492500561',
        primaryImageUrl: 'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        imageUrls: [
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        ],
        isIndoor: true,
        hasShower: true,
        hasParking: true,
        city: 'İstanbul',
        district: 'Bahçelievler',
      ),
    ],
    'Güngören': [
      Halisaha(
        name: 'Oktay Halısahası',
        latitude: 40.97297,
        longitude: 29.15019,
        mapLink: 'https://maps.app.goo.gl/XM2AWVesZdM6TuWQ6',
        phoneNumber: '02125059095',
        primaryImageUrl: 'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        imageUrls: [
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        ],
        isIndoor: true,
        hasShower: true,
        hasParking: true,
        city: 'İstanbul',
        district: 'Güngören',
      ),

      Halisaha(
        name: 'Lider Halısahası',
        latitude: 40.97297,
        longitude: 29.15019,
        mapLink: 'https://maps.app.goo.gl/cZVp8kjph881e4HB7',
        phoneNumber: '02125628080',
        primaryImageUrl: 'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        imageUrls: [
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        ],
        isIndoor: true,
        hasShower: true,
        hasParking: true,
        city: 'İstanbul',
        district: 'Güngören',
      ),
      Halisaha(
        name: 'Altınova Halısahası',
        latitude: 40.97297,
        longitude: 29.15019,
        mapLink: 'https://maps.app.goo.gl/GsR7kLzbc5rpEe6R9',
        phoneNumber: '0212 600 87 00',
        primaryImageUrl: 'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        imageUrls: [
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
          'https://th.bing.com/th/id/OIG2.baoCTFoEvQFW51Lk2gew?pid=ImgGn',
        ],
        isIndoor: true,
        hasShower: true,
        hasParking: true,
        city: 'İstanbul',
        district: 'Güngören',
      ),
    ],
  },
};


class Halisaha {
  final String name;
  final double latitude;
  final double longitude;
  final String mapLink;
  final String phoneNumber;
  final String primaryImageUrl;
  final List<String> imageUrls; // Birden fazla resim URL'sini saklamak için liste kullanıyoruz
  final bool isIndoor;
  final bool hasShower;
  final bool hasParking;
  final String city;
  final String district;

  Halisaha({
    required this.name,
    required this.latitude,
    required this.longitude,
    required this.mapLink,
    required this.phoneNumber,
    required this.primaryImageUrl,
    required this.imageUrls,
    required this.isIndoor,
    required this.hasShower,
    required this.hasParking,
    required this.city,
    required this.district,
  });
}


